---
version: '3'

services:
  app:
    build: ./app
    read_only: true
    environment:
      - FLAG=Hero{ba7b97ae00a760b44cc8c761e6d4535b}
    expose:
      - 3000
    networks:
      referrrrer:
        ipv4_address: 10.100.1.100

  nginx:
    image: nginx:stable-alpine
    read_only: true
    ports:
      - "7000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    tmpfs:
      - /var/cache/nginx/:uid=0,gid=0,size=50M,noexec
      - /run/:uid=0,gid=0,size=10M,noexec
    networks:
      referrrrer:
        ipv4_address: 10.100.1.101
    depends_on:
      - app

networks:
  referrrrer:
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.1.100/24
